agent:
  model:
    name: deepseek/deepseek-chat
    api_base: https://api.deepseek.com/v1
    api_key: $DEEPSEEK_API_KEY
    temperature: 0.0
    per_instance_cost_limit: 0.01

env:
  repo:
    github_url: https://github.com/SWE-agent/test-repo

problem_statement:
  github_url: https://github.com/SWE-agent/test-repo/issues/1